name: Test workflow
on: push
jobs:
  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: 'actions/checkout@master'

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies

        run: npm install

      - name: Lint sources
        run: npm run lint:js-fix

      - name: 'Check for uncommitted changes'
        run: |
          git diff --exit-code --stat -- . \
          || (echo "##[error] found changed files after build. please 'npm install && npm run lint && npm run test'" \
                   "and check in all changes" \
              && exit 1)
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: 'actions/checkout@master'

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies

        run: npm install

      - name: Run tests
        run: npm run test
